// src/pages/PrivacyPolicy.tsx
//
// Public, unauthenticated page. Renders the content of
// docs/PRIVACY_POLICY.md as React so it needs no markdown-parsing
// dependency. Edit the text below directly — this file IS the source of
// truth once it's live; keep docs/PRIVACY_POLICY.md in sync if you want a
// plain-text copy for lawyers to review outside the app.
//
// Wherever you see [HOTEL NAME], it's pulled live from HotelDetailsContext
// (the same name shown in the app's navbar) so you only ever set it once.

import { Link } from "@tanstack/react-router";
import { useHotelDetails } from "@/contexts/HotelDetailsContext";

const LAST_UPDATED = "2026-08-13"; // bump this whenever the text below changes

function LegalShell({
  title,
  hotelName,
  children,
}: {
  title: string;
  hotelName: string;
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <Link to="/login" className="text-sm text-muted-foreground hover:underline">
          &larr; Back
        </Link>
        <h1 className="mt-4 text-3xl font-bold">
          {title} — {hotelName || "[HOTEL NAME]"}
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Last updated: {LAST_UPDATED}. Draft prepared for legal review — not
          final until approved by qualified counsel.
        </p>
        <div className="prose prose-sm mt-8 max-w-none dark:prose-invert">
          {children}
        </div>
      </div>
    </div>
  );
}

export default function PrivacyPolicy() {
  const { details } = useHotelDetails();
  const hotelName = details.hotelName;

  return (
    <LegalShell title="Privacy Policy" hotelName={hotelName}>
      <h2>1. Who we are</h2>
      <p>
        {hotelName || "[HOTEL NAME]"} ("we", "us", "the Hotel") operates a
        guest management system to process bookings, register guests as
        required by law, and manage your stay. This policy explains what
        personal data we collect, why, how long we keep it, and what rights
        you have over it.
      </p>
      <p>
        <strong>Contact for privacy questions:</strong> [EMAIL / PHONE / ADDRESS]
      </p>

      <h2>2. What we collect</h2>
      <table>
        <thead>
          <tr>
            <th>Category</th>
            <th>Examples</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Identity &amp; contact</td>
            <td>Full name, phone, WhatsApp, email, Telegram, Instagram</td>
            <td>Provided by you at booking/check-in</td>
          </tr>
          <tr>
            <td>Government ID</td>
            <td>
              Passport name, birth date, issue date, citizenship, gender
            </td>
            <td>Provided by you at check-in, required by law</td>
          </tr>
          <tr>
            <td>Stay details</td>
            <td>
              Check-in/out dates, room, guest count, price, payment method
            </td>
            <td>Generated when you book</td>
          </tr>
          <tr>
            <td>Communications</td>
            <td>Notes staff record about your stay</td>
            <td>Generated by hotel staff</td>
          </tr>
        </tbody>
      </table>
      <p>
        We do <strong>not</strong> collect payment card numbers in this
        system — payment method is recorded only as a category (cash / card
        / transfer), not card details.{" "}
        <em>(Confirm this matches your actual payment processing.)</em>
      </p>

      <h2>3. Why we collect it (legal basis)</h2>
      <ul>
        <li>
          <strong>Passport/ID data:</strong> collected because [applicable
          hotel-registration law/regulation — fill in with your lawyer]
          requires hotels to register guests' identity documents.
        </li>
        <li>
          <strong>Contact details:</strong> collected to confirm bookings,
          communicate about your stay, and follow up if needed — with your
          consent, given by completing check-in.
        </li>
        <li>
          <strong>Stay/payment records:</strong> collected to provide the
          service you booked and to meet accounting/tax record-keeping
          obligations.
        </li>
      </ul>

      <h2>4. How long we keep it</h2>
      <ul>
        <li>
          Booking and passport records: kept for [X years] after checkout,
          then deleted.
        </li>
        <li>Login/security logs: kept for 30 days, then automatically purged.</li>
      </ul>
      <p>
        <em>
          This section must be filled in with your actual retention period
          before publishing.
        </em>
      </p>

      <h2>5. Who can see your data</h2>
      <p>
        Your data is visible only to authorized hotel staff (front desk /
        manager / director / superuser roles) for the purpose of operating
        your stay. We do not sell your data. We do not share it with third
        parties except:
      </p>
      <ul>
        <li>Where required by law (e.g. government hotel-registration systems).</li>
        <li>
          Service providers who host our systems (Supabase, our database and
          booking-sync provider; Vercel, our website hosting provider) —
          both act only on our instructions.
        </li>
      </ul>

      <h2>6. Your rights</h2>
      <p>
        Depending on applicable law, you may have the right to request a
        copy of your data, ask us to correct inaccurate data, or ask us to
        delete it once it's no longer legally required to be kept. To make a
        request, contact us at [EMAIL].
      </p>

      <h2>7. Security</h2>
      <p>
        We store your data in an access-controlled database. Staff accounts
        require a password to sign in, and repeated failed sign-in attempts
        are automatically blocked to protect against unauthorized access. No
        system is perfectly secure, and we cannot guarantee absolute
        security of data transmitted to us.
      </p>

      <h2>8. Changes to this policy</h2>
      <p>
        We may update this policy from time to time. The "Last updated"
        date above reflects the latest revision.
      </p>

      <hr />
      <p className="text-xs text-muted-foreground">
        This document was drafted to accurately reflect what the{" "}
        {hotelName || "[HOTEL NAME]"} booking system technically collects. It
        is a starting point for a lawyer to finalize against the specific
        laws that apply to your hotel — it is not itself legal advice and
        should not be relied on as final until reviewed by qualified
        counsel.
      </p>
    </LegalShell>
  );
}
